apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: somebot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/richarddrochner/somebot'
    targetRevision: HEAD
    path: 'kubernetes'
  project: default