apiVersion: apps/v1
kind: Deployment
metadata:
  name: somebot-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: somebot
  template:
    metadata:
      labels:
        app: somebot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: somebot
        image: ghcr.io/richarddrochner/somebot:latest
        workingDir: /app
        env:
        - name: OLLAMA_HOST
          value: "ollama-service:11434"
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: somebot-secrets
              key: discord-webhook-url
        - name: MODEL_HUMOR
          value: "model_humor.txt"
        volumeMounts:
          - name: app-volume
            mountPath: /app
      volumes:
          - name: app-volume
            emptyDir: { }
      imagePullSecrets:
        - name: somebot-secret